version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: code-context-qdrant
    ports:
      - "6333:6333"  # REST API port
      - "6334:6334"  # gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Ollama service for local embeddings
  # Uncomment if you want to run Ollama locally
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: code-context-ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./ollama_data:/root/.ollama
  #   restart: unless-stopped
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0
